export default interface Project {
    projectId: number,
    projectName: string,
    creatorName: string,
    type: string,
    startDate: string,
    endDate: string,
    tag: string,
    submitted: boolean,
    accepted:boolean,
    projectIntro: string,
    testAndAppFile: string,
    num:number,
    sum:number,
    peopleSituation:string,
    device: string,
    environment: string,
    language: Array<string>,
    method:string,
    rank:number,
    area:string,
    finishedPeople:number,
    costSum: number,
}