export default interface UploadTask{
    projectName: string,
    type: string,
    startDate: Date,
    startTime: Date,
    endDate: Date,
    endTime: Date,
    num:number,
    projectIntro: string,
    appFile: File,
    testFile: File,
    device: string,
    environment: string,
    language: Array<string>,
    method:string,
    rank:string,
    area:string,
    costSum:number,
}